#!/data/data/com.termux/files/usr/bin/bash




pdir=$HOME/.awnto
pfol=rnx-d
pfll=$pdir/$pfol

mkdir -p $pfll

cd $pdir

echo ""
echo ""

arch=`uname -m`

echo "architecture : $arch "

case $arch in
aarch64)
rnx_tn=rnx-d-cross.tar.gz
rnx_tar_link=http://rinix.awnto.com/rnx-get/files/$rnx_tn
#echo -n ""
#exit 

;;


arm64)
rnx_tn=rnx-d-cross.tar.gz
rnx_tar_link=http://rinix.awnto.com/rnx-get/files/$rnx_tn
#echo -n ""
#exit 

;;



armv7l)
rnx_tn=rnx-d-cross.tar.gz
rnx_tar_link=http://rinix.awnto.com/rnx-get/files/$rnx_tn
#echo -n ""
#exit 

;;

*)


archi=`dpkg --print-architecture`

	echo "no direct using package architecture : $archi "



	case $archi in
	arm)
	
	rnx_dae=http://rinix.awnto.com/rnx-get/files/dae/dae-armhf

	
	;;
	
*)

echo "no supported : $arch "

echo ""
echo "kindly contact "
echo "https://rinix.awnto.com"
echo ""
echo ""
echo "or run this after some days"
echo ""
exit ;;

esac


esac


if ! wget -O $rnx_tn $rnx_tar_link ;
then
	exit
fi



#tar -xvf /sdcard/AWN/proj/rnx/rnx-d.tar.xz

echo "executing backup program"
if test -f ./$pfol/backup ;
then
	echo "backing data"
	./$pfol/backup
else
	echo "no data for backing"
fi

echo "--------------"
rm -rvf $pfol
echo "--------------"
#cp -rvf /sdcard/AWN/proj/rnx/$pfol .

tar -xzvf $rnx_tn

echo "--------------"
chmod -R 755 $pfol
echo "--------------"


exec ./$pfol/trigger






